version: "3.7"

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    networks:
      - my_network
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    networks:
      - my_network
    ports:
      - "29092:29092"
      - "9092:9092" 
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  spark:
    build: . # Ici, '.' signifie le répertoire actuel où se trouve votre docker-compose.yml et Dockerfile
    container_name: spark
    networks:
      - my_network
    ports:
      - "8080:8080" # Web UI
      - "7077:7077" # Spark master
      - "4040:4040" # Spark context web UI (peut varier si plusieurs jobs)
      - "8888:8888" # Port pour Jupyter Notebook
    volumes:
      - C:/Users/dell/Desktop/big-data:/opt/bitnami/spark/data
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_DRIVER_MEMORY=2g
      - SPARK_EXECUTOR_MEMORY=2g
      - SPARK_DRIVER_CORES=2
      - SPARK_EXECUTOR_CORES=2
    depends_on:
      - kafka

  mongodb:
    image: mongo:latest
    container_name: mongo
    networks:
      - my_network
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:

networks:
  my_network:
    driver: bridge
